# Generated by Django 3.2.8 on 2021-11-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_num_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
