# Generated by Django 3.0.14 on 2022-01-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220112_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Categories'},
        ),
    ]
