# Generated by Django 3.0.14 on 2022-02-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_footer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
