# Generated by Django 3.0.14 on 2022-02-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_image_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_footer',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
